spring.datasource.url=jdbc:mysql://localhost:3306/register
spring.datasource.username=root
spring.datasource.password=royaleconcursos5

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
